name: learn-github_actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - uses: actions/checkout@v3
      - run: npm i && npm run build
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: build
          path: dist
